version: '3.9'

services:
  spz:
    build: .
    container_name: spz
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.spz.rule=Host(`spz.poetika.online`)
      - traefik.http.routers.spz.entrypoints=websecure
      - traefik.http.routers.spz.tls.certresolver=letsencrypt
      # voliteľne redirect HTTP→HTTPS
      - traefik.http.routers.spz.middlewares=redirect-to-https

networks:
  proxy:
    external: true
